/**
 * This file is generated by the 'firebase-backend-ts-scaffold' utility.
 * It is not intended for manual editing. Any changes made here may be overwritten.
 *
 * This file provides TypeScript interfaces that correspond to the JSON schema
 * definitions in the `backend.json` file. These interfaces are used throughout
 * the application for type-safe interaction with Firestore data.
 */

export interface UserProfile {
  /**
   * User's first name.
   */
  firstName: string;
  /**
   * User's last name.
   */
  lastName: string;
  /**
   * User's email address.
   */
  email: string;
  /**
   * Unique identifier for the user profile, matches Firebase Auth UID.
   */
  id: string;
  /**
   * URL to the user's LinkedIn profile.
   */
  linkedInProfile?: string;
  /**
   * URL to the user's GitHub profile.
   */
  gitHubProfile?: string;
  /**
   * List of skills possessed by the user.
   */
  skills?: string[];
  /**
   * Job preferences like remote, hybrid or on-site.
   */
  jobPreferences?: string;
  /**
   * Reference to Resume. (Relationship: UserProfile 1:1 Resume)
   */
  resumeId?: string;
  [k: string]: any;
}

export interface Resume {
  /**
   * Unique identifier for the resume.
   */
  id: string;
  /**
   * Reference to UserProfile. (Relationship: UserProfile 1:1 Resume)
   */
  userId: string;
  /**
   * The date and time the resume was uploaded.
   */
  uploadDate: string;
  /**
   * URL where the resume file is stored.
   */
  fileUrl: string;
  [k: string]: any;
}

export interface Job {
  /**
   * Unique identifier for the Job.
   */
  id: string;
  /**
   * Company name.
   */
  company: string;
  /**
   * Job Role.
   */
  role: string;
  /**
   * List of requirements for the Job.
   */
  requirements: string[];
  [k: string]: any;
}

export interface GeneratedResume {
  /**
   * The ID of the user who owns this resume.
   */
  userId: string;
  /**
   * The job description used to generate the resume.
   */
  jobDescription: string;
  /**
   * The full content of the generated resume in Markdown.
   */
  resumeContent: string;
  /**
   * The date and time the resume was generated.
   */
  createdAt: string;
  [k: string]: any;
}

export interface QuizAttempt {
  /**
   * Unique identifier for the quiz attempt.
   */
  id: string;
  /**
   * The ID of the user who took the quiz.
   */
  userId: string;
  /**
   * The topic of the quiz (e.g., Python, React).
   */
  topic: string;
  /**
   * The number of correct answers.
   */
  score: number;
  /**
   * The total number of questions in the quiz.
   */
  totalQuestions: number;
  /**
   * The date and time the quiz was completed.
   */
  completedAt: string;
  [k: string]: any;
}

export interface SuggestedJob {
  /**
   * The ID of the user for whom the job was suggested.
   */
  userId: string;
  /**
   * The title of the job role.
   */
  title: string;
  /**
   * The company offering the job.
   */
  company: string;
  /**
   * A brief description of the job.
   */
  description: string;
  /**
   * A score indicating how relevant the job is to the user.
   */
  relevanceScore: number;
  /**
   * The timestamp when the job suggestion was created.
   */
  createdAt: string;
  /**
   * The location of the job.
   */
  location?: string;
  /**
   * List of skills required for the job.
   */
  skills?: string[];
  [k: string]: any;
}

export interface Course {
  /**
   * Unique identifier for the course.
   */
  id: string;
  /**
   * The title of the course.
   */
  title: string;
  /**
   * A brief description of the course.
   */
  description: string;
  /**
   * The category of the course (e.g., Data Structures, Web Development).
   */
  category: string;
  /**
   * An array of lessons in the course.
   */
  lessons: {
    title?: string;
    type?: "video" | "text";
    content?: string;
    [k: string]: any;
  }[];
  [k: string]: any;
}
