import type { Course } from "@/docs/backend-documentation";

// This is Omit<Course, "id"> because the ID will be generated by Firestore.
export const placementCourses: Omit<Course, "id">[] = [
  {
    title: "Data Structures & Algorithms in JavaScript",
    description: "Master essential data structures and algorithms using JavaScript. A crucial skill for any coding interview.",
    category: "Technical",
    lessons: [
      { title: "Introduction to Big O Notation", type: "video", content: "video_url_placeholder" },
      { title: "Arrays and Strings", type: "text", content: "Detailed notes on array and string manipulations." },
      { title: "Linked Lists", type: "video", content: "video_url_placeholder" },
      { title: "Stacks and Queues", type: "video", content: "video_url_placeholder" },
      { title: "Trees (Binary, BST, AVL)", type: "text", content: "Comprehensive guide to tree structures." },
      { title: "Graphs and Graph Traversal (BFS, DFS)", type: "video", content: "video_url_placeholder" },
      { title: "Sorting Algorithms", type: "text", content: "Comparison of different sorting algorithms." },
      { title: "Recursion and Dynamic Programming", type: "video", content: "video_url_placeholder" },
    ]
  },
  {
    title: "System Design Fundamentals",
    description: "Learn the principles of designing scalable and reliable systems. A key topic for senior roles.",
    category: "System Design",
    lessons: [
      { title: "Vertical vs. Horizontal Scaling", type: "text", content: "Understanding scaling strategies." },
      { title: "Load Balancing", type: "video", content: "video_url_placeholder" },
      { title: "Database Sharding and Replication", type: "video", content: "video_url_placeholder" },
      { title: "Caching Strategies (Redis, Memcached)", type: "text", content: "Notes on effective caching." },
      { title: "Designing a URL Shortener", type: "video", content: "video_url_placeholder" },
      { title: "Designing a Social Media Feed", type: "video", content: "video_url_placeholder" },
      { title: "CAP Theorem", type: "text", content: "Exploring consistency, availability, and partition tolerance." }
    ]
  },
  {
    title: "Advanced React and State Management",
    description: "Go beyond the basics of React with advanced hooks, patterns, and state management libraries.",
    category: "Frontend",
    lessons: [
      { title: "Deep Dive into Hooks (useMemo, useCallback, useRef)", type: "video", content: "video_url_placeholder" },
      { title: "Render Props and Higher-Order Components", type: "text", content: "Advanced component patterns." },
      { title: "State Management with Redux Toolkit", type: "video", content: "video_url_placeholder" },
      { title: "State Management with Zustand", type: "video", content: "video_url_placeholder" },
      { title: "React Performance Optimization", type: "text", content: "Techniques for a faster React app." },
      { title: "Introduction to React Server Components", type: "video", content: "video_url_placeholder" },
    ]
  },
  {
    title: "Mastering SQL for Data Science",
    description: "From basic queries to advanced window functions, become proficient in SQL for data analysis and interviews.",
    category: "Data Science",
    lessons: [
        { title: "Complex Joins", type: "video", content: "video_url_placeholder" },
        { title: "Window Functions", type: "text", content: "Detailed guide on window functions." },
        { title: "Common Table Expressions (CTEs)", type: "video", content: "video_url_placeholder" },
        { title: "Query Optimization", type: "text", content: "Tips for writing efficient SQL queries." },
    ]
  },
  {
    title: "Behavioral Interview Prep",
    description: "Learn how to effectively answer behavioral questions using the STAR method and showcase your soft skills.",
    category: "Soft Skills",
    lessons: [
      { title: "The STAR Method Explained", type: "video", content: "video_url_placeholder" },
      { title: "Answering 'Tell me about a time you failed.'", type: "text", content: "Strategies for tough questions." },
      { title: "Communicating Your Strengths", type: "video", content: "video_url_placeholder" },
      { title: "Asking Insightful Questions to the Interviewer", type: "text", content: "How to show engagement." }
    ]
  }
];
